// for setting language
export const SET_LANGUAGE = 'SET_LANGUAGE';
// for sign in
export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
// for sign out
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
// for sign up
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
// make error true
export const MAKE_ERROR_FALSE = "MAKE_ERROR_FALSE";
export const FETCHING_USER = "FETCHING_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const UPDATE_USERPROFILE_SUCCESS = "UPDATE_USERPROFILE_SUCCESS";
// Common
export const HOME_BANNER_SUCCESS = "HOME_BANNER_SUCCESS";
export const COMMON_ACTION_FAILURE = "COMMON_ACTION_FAILURE";
export const COMMON_ACTION_REQUEST = "COMMON_ACTION_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const NEWS_COMMUNITY_SUCCESS = "NEWS_COMMUNITY_SUCCESS";